module.exports = [
  "800 Services",
  "Administrative",
  "Allocations",
  "Benefits",
  "Bonus Incentive Plan",
  "Bonus",
  "Business Software",
  "CIP Labor",
  "Capital Investments",
  "Capitalized External Labor",
  "Capitalized Facilities",
  "Capitalized Hardware",
  "Capitalized Internal Labor",
  "Capitalized Labor",
  "Capitalized Software",
  "Capitalized Technology",
  "Capitalized Telecom",
  "Company Memberships",
  "Computing Tech Services",
  "Consulting Services",
  "Consulting",
  "Contract Admin labor",
  "Contract Labor",
  "Contract Tech labor",
  "Data Center",
  "Databasse Software & Tools",
  "Dedicated Data Transmission Facilities & Power",
  "Dedicated Voice Transmission Facilities & Power",
  "Department Labor Transfer In",
  "Department Labor Transfer Out",
  "Depr - Bldg and land Improvemts",
  "Depr - Capital Leases",
  "Depr - Computer Equipment",
  "Depr - Computer Software",
  "Depr - Leasehold Improvements",
  "Depr - Office Equipment",
  "Depr - Office FFE",
  "Depr - Real estate assets",
  "Depr - Software Development",
  "Depr - Vehicles",
  "Depreciation",
  "EDI",
  "Electricity & Other Utilities",
  "Employee Agency Services",
  "Employee Benefits",
  "Employee Recruitment",
  "Employee Training & Devel. - Travel",
  "Employee Training & Development",
  "Entertainment",
  "Equipment",
  "FUI - Federal Unemployment Insurance",
  "Facilities & Power",
  "Facility & Office Admin",
  "Facility & Office Admin",
  "Facility Raised Floor & Space Rentals",
  "Furniture & Equipment",
  "Hardware Lease",
  "Hardware Maintenance",
  "Hardware",
  "IaaS/PaaS Services",
  "Incentive Stock",
  "Insurance - Dental Plan",
  "Insurance - Group Medical",
  "Insurance",
  "Insurance",
  "Internet Provider Fee",
  "Janitorial Services",
  "Labor Transfer In OpEx",
  "Labor Transfer Out",
  "Local Phone Service",
  "Long Distance Services",
  "Mainframe Equipment & Supplies",
  "Mainframe Hardware",
  "Mainframe Maintenance",
  "Mainframe Software & Tools",
  "Meals & Entertainment",
  "Memberships",
  "Message Handling Svcs",
  "Moving Allowances",
  "Network Equipment Maintenance & Repairs",
  "Network Tech Services",
  "Office Lease",
  "Office Space",
  "Operations Support Services",
  "Other Admin Support",
  "Other Employee Costs",
  "Other Staff Costs",
  "Outside Services - Other",
  "Outside Services",
  "Outside Services",
  "Outsourcing Services",
  "Outsourcing Services",
  "Overtime",
  "PC Equipment & Supplies",
  "PC Maintenance & Repairs",
  "PC Software",
  "Professional Memberships - Individual",
  "Real Estate & Facilities",
  "Records & Retention",
  "Recruiting",
  "Salaries & Benefits",
  "Salaries",
  "Salaries/Wages",
  "Server Equipment & Supplies",
  "Server Maintenance & Repairs",
  "Service Transfers In",
  "Service Transfers Out",
  "Severance Pay",
  "Social Club Dues & Memberships",
  "Software as a Service",
  "Software",
  "Software",
  "Systems Software & Tools",
  "Tech Services",
  "Technology",
  "Telecom Equipment & Supplies",
  "Telecom",
  "Telecomm Tech Services",
  "Telecommunications Equipment",
  "Training",
  "Travel & Entertainment",
  "Travel Expense - Lodging",
  "Travel Expense - Other",
  "Travel Expense- Transportation",
  "Vacation Accrued",
  "Voice",
  "WAN",
  "Wages",
];
