module.exports = [
  "App Dev & Support",
  "Apps - Back Office",
  "Apps - Line of Business",
  "Apps - Sales & Ops",
  "Collaboration & Communication",
  "Data Center Ops",
  "End User Services",
  "Enterprise Compute & Storage",
  "Field Supprt - NA",
  "Infrastructure & Ops",
  "Network Services",
  "Office of the CIO",
  "Operations Center",
  "Program Office",
  "Security & Risk Mgmt",
  "Service Desk",
  "Voice and Call Center",
];
