module.exports = [
  "365 Main",
  "AT&T",
  "Accenture",
  "Acme Inc.",
  "Adobe",
  "Akamai",
  "Amazon Web Services, Inc.",
  "Apptio",
  "Aspect",
  "Atlassian",
  "Avaya",
  "Avici Tech Services",
  "BMC",
  "BlackBerry Limited",
  "British Telecom",
  "CheckPoint",
  "Cisco Systems",
  "Clarity Software Solutions",
  "Cognos",
  "CompUSA",
  "CompuCom Systems",
  "Concur",
  "Datatrend Technologies",
  "Dell Systems",
  "Documentum",
  "Dyno Tech Services",
  "EMC",
  "Eloqua",
  "GE Capital",
  "HCL",
  "Hewlett Packard",
  "Hitachi Data Systems",
  "Hyperion",
  "IBM Services",
  "IBM",
  "Internap",
  "Iron Mountain",
  "KPMG",
  "Kelly Temps",
  "Level 3",
  "Lombardi Software",
  "Lyris Technology",
  "McAfee",
  "Microsoft Azure",
  "Microsoft",
  "Minitab",
  "Modis",
  "NetQOS",
  "Nice Systems",
  "Nlyte",
  "Oracle Services",
  "Oracle",
  "Paragon Software",
  "PhaseWare",
  "PointB Consulting",
  "Qlik",
  "Redhat",
  "SAP",
  "Salesforce.com",
  "Savvis",
  "Slalom Consulting",
  "Splunk",
  "TDK Technologies",
  "Tableau",
  "Toad",
  "TrendMicro",
  "Troux",
  "VMWare",
  "Verizon",
  "Workday",
  "ZenDesk",
  "networkIQ",
];
